name: Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    env:
      GO111MODULE: off

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.6'

      - name: Run tests
        run: make test
